spring:
  data:
    cassandra:
      contactPoints: 127.0.0.1
      port: 9042
      keyspace: vasp
      username: cassandra
      password: cassandra
      dc: datacenter1
  artemis:
    broker-url: ${ARTEMIS_BROKER_URL:tcp://localhost:61616}
    user: ${ARTEMIS_USERNAME:admin}
    password: ${ARTEMIS_PASSWORD:admin}
    mode: native
  main:
    allow-bean-definition-overriding: true
  application:
    name: topup
RABBITMQ_HOST: localhost
RABBITMQ_PORT: 5672
RABBITMQ_USERNAME: guest
RABBITMQ_PASSWORD: guest
RABBITMQ_EXCHANGE_NAME: exchange
RABBITMQ_QUEUE_TOPUP: billing.charge.queue
RABBITMQ_ROUTING_KEY_TOPUP: billing.charge.queue
RABBITMQ_VIRTUAL_HOST: /
logging:
  file.name: logs/topup.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  level:
    org.springframework.web: ERROR
    uz.ucell.topup: INFO
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,metrics
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  prometheus:
    metrics:
      export:
        enabled: true
